apiVersion: v1
kind: Service
metadata:
  name: simple-web
  namespace: default
spec:
  selector:
    app: simple-web
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: simple-web
    protocol: TCP
    port: 8080
    targetPort: simple-web